### PR TITLE
Fallback to GET for HEAD requests

### PR DESCRIPTION
**Pull request by garyburd**

### CODE REVIEW

**Comment by moraes** [comment]
So...

If a HEAD handler is not explicitly defined by the user, why not try the catch-all handler first (since it's also explicitly defined), before trying the GET fallback?

It sounds like someone would want to set a catch-all handler to really catch all request methods. No?

**Comment by garyburd** [comment]
The HEAD method is identical to GET except that the response body is not returned. Because the net/http server [discards the response body for the HEAD method](https://github.com/golang/go/blob/f6fd086d5ef25e4d9edc953aa1a5b75a475abebb/src/net/http/server.go#L265-L268), this fallback enables correct handling of the HEAD method without any explicit code for HEAD in the application.

**Comment by moraes** [comment]
My question is more in the line of "If I set a catch-all handler, why do you still handle HEAD requests for me? Wasn't it supposed to catch *all* methods?".

The fallback would still be in place, just not used by who doesn't want any fallback (and for that reason used a catch-all handler).

```go
r.Pattern("foo").Get(showFoo).Post(saveFoo) // magical handling of HEAD
r.Pattern("foo").Handle(everythingFoo)      // no HEAD handling. let me do it
```

Maybe it doesn't make any sense to not want it?

**Comment by garyburd** [comment]
The problem scenario is:

    r.Route("/foo").Get(showFoo).Handle(everythingFoo)

Should HEAD dispatch to `showFoo` or `everythingFoo`? 

The easiest way to write a HEAD handler is to add an if statement to the GET handler.  If the developer handles HEAD this way, then dispatching to `showFoo` is convenient.

If the developer did not write code to handle HEAD, then dispatching to `showFoo` results in correct handling of the method.

The developer can force dispatch of HEAD to `everythingFoo`:

    r.Route("/foo").Get(showFoo).Handle(everythingFoo).Head(everythingFoo)

This is  verbose, but that's OK. This is not a common scenario.

Either way, the HEAD fallback precedence should be documented.

**Pull request merged**
